### ISSUE TITLE
Annoying exception when closing Fluo client

### ISSUE THREAD

**Issue by keith-turner** [fluo-io/fluo#489]
I am working on bring the phrasecount example up to date with beta snapshot.  While running the phrasecount print command, I kept seeing the following exception.  I think this is happening when FluoClient is closed.

```
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2095)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:389)
	at io.fluo.core.oracle.OracleClient$TimestampRetriever.doWork(OracleClient.java:157)
	at io.fluo.core.oracle.OracleClient$TimestampRetriever.run(OracleClient.java:111)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by keith-turner** [comment]
Nevermind, this not a problem.   Phrasecount had enabled debug logging for Fluo.   The exception was logged at debug, it would normally not be seen.

```
2015-04-27 11:52:44,239 [oracle.OracleClient] DEBUG: InterruptedException occurred in doWork() method
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2095)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:389)
	at io.fluo.core.oracle.OracleClient$TimestampRetriever.doWork(OracleClient.java:157)
	at io.fluo.core.oracle.OracleClient$TimestampRetriever.run(OracleClient.java:111)
	at java.lang.Thread.run(Thread.java:745)
```
