### ISSUE TITLE
Saw NotificationGcIT fail on travis build

### ISSUE THREAD

**Issue by keith-turner** [fluo-io/fluo#555]
Saw build [#736](https://travis-ci.org/fluo-io/fluo/builds/80481637) fail against f5f2625

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.151 sec <<< FAILURE! - in io.fluo.integration.impl.NotificationGcIT
testNotificationGC(io.fluo.integration.impl.NotificationGcIT)  Time elapsed: 5.147 sec  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.fluo.integration.impl.NotificationGcIT.testNotificationGC(NotificationGcIT.java:80)
```

**Comment by keith-turner** [comment]
Saw this test fail again against 2cf3dd4.  Was trying to build against Accumulo 1.7.1 RC2, but I don't think that was related.

```
Running io.fluo.integration.impl.NotificationGcIT
r1 ntfy:%04;stat%05;check [] 33 false=
r1 ntfy:%04;stat%05;check [] 25 false=
r1 ntfy:%04;stat%05;check [] 16 false=
r2 ntfy:%04;stat%05;check [] 27 false=
r2 ntfy:%04;stat%05;check [] 20 false=
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.576 sec <<< FAILURE! - in io.fluo.integration.impl.NotificationGcIT
testNotificationGC(io.fluo.integration.impl.NotificationGcIT)  Time elapsed: 2.572 sec  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.fluo.integration.impl.NotificationGcIT.assertRawNotifications(NotificationGcIT.java:47)
	at io.fluo.integration.impl.NotificationGcIT.testNotificationGC(NotificationGcIT.java:89)
```

**Comment by keith-turner** [comment]
Saw this fail again on travis build of #817

```
Running org.apache.fluo.integration.impl.NotificationGcIT
2017-03-23 17:27:57,321 [impl.NotificationGcIT] ERROR: r1 ntfy:%04;stat%05;check [] 55 false=
2017-03-23 17:27:57,321 [impl.NotificationGcIT] ERROR: r1 ntfy:%04;stat%05;check [] 31 false=
2017-03-23 17:27:57,321 [impl.NotificationGcIT] ERROR: r1 ntfy:%04;stat%05;check [] 16 false=
2017-03-23 17:27:57,321 [impl.NotificationGcIT] ERROR: r2 ntfy:%04;stat%05;check [] 57 false=
2017-03-23 17:27:57,321 [impl.NotificationGcIT] ERROR: r2 ntfy:%04;stat%05;check [] 33 false=
2017-03-23 17:27:57,321 [impl.NotificationGcIT] ERROR: r2 ntfy:%04;stat%05;check [] 20 false=
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.708 sec <<< FAILURE! - in org.apache.fluo.integration.impl.NotificationGcIT
testNotificationGC(org.apache.fluo.integration.impl.NotificationGcIT)  Time elapsed: 2.705 sec  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<6>
	at org.apache.fluo.integration.impl.NotificationGcIT.assertRawNotifications(NotificationGcIT.java:51)
	at org.apache.fluo.integration.impl.NotificationGcIT.testNotificationGC(NotificationGcIT.java:97)
```
