### ISSUE TITLE
Improve error message for invalid initialization.properties

### ISSUE THREAD

**Issue by mikewalch** [fluo-io/fluo#64]
My observer configuration was old and caused the exception below.  The InitializeTool should instead print an error mesage that the observer config is improperly formatted and exit initialization rather than just printing a stack trace.
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at accismus.api.Admin.addObserver(Admin.java:140)
	at accismus.api.Admin.updateWorkerConfig(Admin.java:115)
	at accismus.api.Admin.initialize(Admin.java:75)
	at accismus.tools.InitializeTool.main(InitializeTool.java:51)
```

**Comment by mikewalch** [comment]
Fixed in PR #399
